server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8

logging:
  #log4j配置文件
  config: classpath:log4j.xml

spring:
  profiles:
    #项目运行环境
    active: dev
  # 404抛出NoHandlerFoundException错误
  mvc:
    throw-exception-if-no-handler-found=: true
    static-path-pattern: /statics/**
  banner:
    charset: UTF-8
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      # 文件最大上传大小
      max-file-size: 70MB
      # 请求最大上传大小
      max-request-size: 70MB
  datasource:
    #druid 数据源专有配置
    druid:
      min-idle: 5
      initial-size: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true

      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true

      #配置监控统计拦截的filters，stat:监控统计、slf4j：日志记录、wall：防御sql注入
      #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
      filters: stat,wall,slf4j
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

sa-token:
  token-name: admin_token
  # token有效期，单位s, -1代表永不过期  当前设置为10天
  timeout: 864000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒 ,-1代表永不过期 当前设置为50分
  activity-timeout: 3000
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
